server:
  port: 8080
spring:
  application:
    name: "pyp-medellin"
  devtools:
    add-properties: false
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongouri"
adapter:
  restconsumer:
    timeout: 5000
    url: "http://192.168.1.1:5000/chat/sendmessage/"
